name: "Publish Site"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Source
      uses: actions/checkout@v4.1.1

    - name: Initialize Nix
      uses: cachix/install-nix-action@v25

    - name: Build Site
      run: nix build

    - name: Workaround File Permissions # See (https://github.com/actions/deploy-pages/issues/58)
      run: cp -r -L --no-preserve=mode,ownership result/site artifact

    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3.0.1
      with:
        path: artifact

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4.0.4
